export type BibleBookSeed = {
  slug: string;
  name: string;
  abbreviation: string;
  testament: "old" | "new";
  chapters: number;
};

export const bibleBooks: BibleBookSeed[] = [
  { slug: "genesis", name: "Gênesis", abbreviation: "Gn", testament: "old", chapters: 50 },
  { slug: "exodo", name: "Êxodo", abbreviation: "Ex", testament: "old", chapters: 40 },
  { slug: "levitico", name: "Levítico", abbreviation: "Lv", testament: "old", chapters: 27 },
  { slug: "numeros", name: "Números", abbreviation: "Nm", testament: "old", chapters: 36 },
  { slug: "deuteronomio", name: "Deuteronômio", abbreviation: "Dt", testament: "old", chapters: 34 },
  { slug: "josue", name: "Josué", abbreviation: "Js", testament: "old", chapters: 24 },
  { slug: "juizes", name: "Juízes", abbreviation: "Jz", testament: "old", chapters: 21 },
  { slug: "rute", name: "Rute", abbreviation: "Rt", testament: "old", chapters: 4 },
  { slug: "1-samuel", name: "1 Samuel", abbreviation: "1Sm", testament: "old", chapters: 31 },
  { slug: "2-samuel", name: "2 Samuel", abbreviation: "2Sm", testament: "old", chapters: 24 },
  { slug: "1-reis", name: "1 Reis", abbreviation: "1Rs", testament: "old", chapters: 22 },
  { slug: "2-reis", name: "2 Reis", abbreviation: "2Rs", testament: "old", chapters: 25 },
  { slug: "1-cronicas", name: "1 Crônicas", abbreviation: "1Cr", testament: "old", chapters: 29 },
  { slug: "2-cronicas", name: "2 Crônicas", abbreviation: "2Cr", testament: "old", chapters: 36 },
  { slug: "esdras", name: "Esdras", abbreviation: "Ed", testament: "old", chapters: 10 },
  { slug: "neemias", name: "Neemias", abbreviation: "Ne", testament: "old", chapters: 13 },
  { slug: "ester", name: "Ester", abbreviation: "Et", testament: "old", chapters: 10 },
  { slug: "jo", name: "Jó", abbreviation: "Jó", testament: "old", chapters: 42 },
  { slug: "salmos", name: "Salmos", abbreviation: "Sl", testament: "old", chapters: 150 },
  { slug: "proverbios", name: "Provérbios", abbreviation: "Pv", testament: "old", chapters: 31 },
  { slug: "eclesiastes", name: "Eclesiastes", abbreviation: "Ec", testament: "old", chapters: 12 },
  { slug: "canticos", name: "Cânticos", abbreviation: "Ct", testament: "old", chapters: 8 },
  { slug: "isaias", name: "Isaías", abbreviation: "Is", testament: "old", chapters: 66 },
  { slug: "jeremias", name: "Jeremias", abbreviation: "Jr", testament: "old", chapters: 52 },
  { slug: "lamentacoes", name: "Lamentações", abbreviation: "Lm", testament: "old", chapters: 5 },
  { slug: "ezequiel", name: "Ezequiel", abbreviation: "Ez", testament: "old", chapters: 48 },
  { slug: "daniel", name: "Daniel", abbreviation: "Dn", testament: "old", chapters: 12 },
  { slug: "oseias", name: "Oséias", abbreviation: "Os", testament: "old", chapters: 14 },
  { slug: "joel", name: "Joel", abbreviation: "Jl", testament: "old", chapters: 3 },
  { slug: "amos", name: "Amós", abbreviation: "Am", testament: "old", chapters: 9 },
  { slug: "obadias", name: "Obadias", abbreviation: "Ob", testament: "old", chapters: 1 },
  { slug: "jonas", name: "Jonas", abbreviation: "Jn", testament: "old", chapters: 4 },
  { slug: "miqueias", name: "Miqueias", abbreviation: "Mq", testament: "old", chapters: 7 },
  { slug: "naum", name: "Naum", abbreviation: "Na", testament: "old", chapters: 3 },
  { slug: "habacuque", name: "Habacuque", abbreviation: "Hc", testament: "old", chapters: 3 },
  { slug: "sofonias", name: "Sofonias", abbreviation: "Sf", testament: "old", chapters: 3 },
  { slug: "ageu", name: "Ageu", abbreviation: "Ag", testament: "old", chapters: 2 },
  { slug: "zacarias", name: "Zacarias", abbreviation: "Zc", testament: "old", chapters: 14 },
  { slug: "malaquias", name: "Malaquias", abbreviation: "Ml", testament: "old", chapters: 4 },
  { slug: "mateus", name: "Mateus", abbreviation: "Mt", testament: "new", chapters: 28 },
  { slug: "marcos", name: "Marcos", abbreviation: "Mc", testament: "new", chapters: 16 },
  { slug: "lucas", name: "Lucas", abbreviation: "Lc", testament: "new", chapters: 24 },
  { slug: "joao", name: "João", abbreviation: "Jo", testament: "new", chapters: 21 },
  { slug: "atos", name: "Atos", abbreviation: "At", testament: "new", chapters: 28 },
  { slug: "romanos", name: "Romanos", abbreviation: "Rm", testament: "new", chapters: 16 },
  { slug: "1-corintios", name: "1 Coríntios", abbreviation: "1Co", testament: "new", chapters: 16 },
  { slug: "2-corintios", name: "2 Coríntios", abbreviation: "2Co", testament: "new", chapters: 13 },
  { slug: "galatas", name: "Gálatas", abbreviation: "Gl", testament: "new", chapters: 6 },
  { slug: "efesios", name: "Efésios", abbreviation: "Ef", testament: "new", chapters: 6 },
  { slug: "filipenses", name: "Filipenses", abbreviation: "Fp", testament: "new", chapters: 4 },
  { slug: "colossenses", name: "Colossenses", abbreviation: "Cl", testament: "new", chapters: 4 },
  { slug: "1-tessalonicenses", name: "1 Tessalonicenses", abbreviation: "1Ts", testament: "new", chapters: 5 },
  { slug: "2-tessalonicenses", name: "2 Tessalonicenses", abbreviation: "2Ts", testament: "new", chapters: 3 },
  { slug: "1-timoteo", name: "1 Timóteo", abbreviation: "1Tm", testament: "new", chapters: 6 },
  { slug: "2-timoteo", name: "2 Timóteo", abbreviation: "2Tm", testament: "new", chapters: 4 },
  { slug: "tito", name: "Tito", abbreviation: "Tt", testament: "new", chapters: 3 },
  { slug: "filemom", name: "Filemom", abbreviation: "Fm", testament: "new", chapters: 1 },
  { slug: "hebreus", name: "Hebreus", abbreviation: "Hb", testament: "new", chapters: 13 },
  { slug: "tiago", name: "Tiago", abbreviation: "Tg", testament: "new", chapters: 5 },
  { slug: "1-pedro", name: "1 Pedro", abbreviation: "1Pe", testament: "new", chapters: 5 },
  { slug: "2-pedro", name: "2 Pedro", abbreviation: "2Pe", testament: "new", chapters: 3 },
  { slug: "1-joao", name: "1 João", abbreviation: "1Jo", testament: "new", chapters: 5 },
  { slug: "2-joao", name: "2 João", abbreviation: "2Jo", testament: "new", chapters: 1 },
  { slug: "3-joao", name: "3 João", abbreviation: "3Jo", testament: "new", chapters: 1 },
  { slug: "judas", name: "Judas", abbreviation: "Jd", testament: "new", chapters: 1 },
  { slug: "apocalipse", name: "Apocalipse", abbreviation: "Ap", testament: "new", chapters: 22 },
];
